defmodule TypeCheck.BuiltinResolutionTest do
  use ExUnit.Case, async: true
  require TypeCheck

  test "allows local functions to use builtin type names" do
    assert NoBuiltinImportsExample.integer() == 42
    assert NoBuiltinImportsExample.binary() == "binary"
    assert NoBuiltinImportsExample.term() == :term
    assert NoBuiltinImportsExample.list(42) == [42]
  end

  test "builds runtime checks from unqualified builtin types" do
    assert TypeCheck.conforms?(42, integer())
    refute TypeCheck.conforms?(:not_an_integer, integer())
    assert TypeCheck.conforms?({:next, :done}, lazy(NoBuiltinImportsExample.recursive()))

    assert NoBuiltinImportsExample.echo_integer(42) == 42
    assert NoBuiltinImportsExample.echo_integer_without_parentheses(42) == 42
    assert TypeCheck.conforms?({:next, :done}, NoBuiltinImportsExample.recursive())
    refute TypeCheck.conforms?({:next, :bad}, NoBuiltinImportsExample.recursive())

    assert TypeCheck.conforms?(
             {:next, {:value, 42}},
             NoBuiltinImportsExample.recursive_value(integer())
           )

    refute TypeCheck.conforms?(
             {:next, {:value, :bad}},
             NoBuiltinImportsExample.recursive_value(integer())
           )

    assert_raise TypeCheck.TypeError, fn ->
      NoBuiltinImportsExample.echo_integer(:not_an_integer)
    end

    assert_raise TypeCheck.TypeError, fn ->
      NoBuiltinImportsExample.list(:not_an_integer)
    end

    assert_raise TypeCheck.TypeError, fn ->
      NoBuiltinImportsExample.echo_integer_without_parentheses(:not_an_integer)
    end
  end

  test "keeps autogenerated typespecs unqualified" do
    {:ok, specs} = Code.Typespec.fetch_specs(NoBuiltinImportsExample)
    {{:echo_integer, 1}, [spec]} = List.keyfind(specs, {:echo_integer, 1}, 0)

    rendered_spec =
      :echo_integer
      |> Code.Typespec.spec_to_quoted(spec)
      |> Macro.to_string()

    assert rendered_spec == "echo_integer(integer()) :: integer()"
    refute rendered_spec =~ "TypeCheck.Builtin"

    {:ok, types} = Code.Typespec.fetch_types(NoBuiltinImportsExample)
    {_kind, wrapped} = Enum.find(types, fn {_kind, {name, _type, _args}} -> name == :wrapped end)
    rendered_type = wrapped |> Code.Typespec.type_to_quoted() |> Macro.to_string()

    assert rendered_type ==
             "wrapped() :: {:wrapped, integer(), binary(), term(), [integer()]}"

    refute rendered_type =~ "TypeCheck.Builtin"

    {_kind, recursive_value} =
      Enum.find(types, fn {_kind, {name, _type, _args}} -> name == :recursive_value end)

    rendered_recursive_value =
      recursive_value |> Code.Typespec.type_to_quoted() |> Macro.to_string()

    assert rendered_recursive_value ==
             "recursive_value(a) :: {:value, a} | {:next, recursive_value(a)}"

    refute rendered_recursive_value =~ "lazy"
  end

  test "builtin constructors remain available through an explicit import" do
    assert TypeCheck.Type.type?(ExplicitBuiltinImportsExample.integer_type())
  end
end
